#include "../include/Map/Lock_Dira.inc" // Закритие дыр по карте
#include "../include/Map/AvtoVokzal_B.inc" // Автовокзал Батырево
#include "../include/Map/Batirevo.inc" 
#include "../include/Map/Bank_B.inc"
#include "../include/Map/AutoShkola_Arzamas.inc"
// #include "../include/Map/Most_Arz_Yjka.inc"

// Работы
#include "../include/Map/Job/Scahta.inc" // Шахта
#include "../include/Map/Job/Lesorub.inc" // Лесоповал
#include "../include/Map/Job/New_Zavod.inc" // Завод
#include "../include/Map/Job/Mysorhic.inc" // 
#include "../include/Map/Job/ShtrafStoyanka.inc" // Штраф-стоянка
// Организации
#include "../include/Map/Frac/DPS.inc"
#include "../include/Map/Frac/FSB.inc"
#include "../include/Map/Frac/VH_Test.inc" 
#include "../include/Map/Frac/VH.inc"
#include "../include/Map/Frac/SMP.inc"
//
#include "../include/Map/DorogaArzamas.inc" 
#include "../include/Map/Rabota_v_Gareli.inc"
#include "../include/Map/MostYjka.inc"
#include "../include/Map/Admins/Admin_House.inc"
#include "../include/Map/Yjka.inc"
#include "../include/Map/Most_Kreml_Litkareno.inc"
// #include "../include/Map/Anashan.inc" // 
#include "../include/Map/Port.inc" // Морской порт
// 
#include "../include/Map/Taxopark.inc" // Таксопарк