
#include "../include/Int/int_autovokzal.inc" // Интерьер Автовокзала

#include "../include/Int/PassportStol.inc" // 
#include "../include/Int/Bank.inc" // Банк
#include "../include/Int/Shaxta.inc" // Шахта
#include "../include/Int/AutoSalon_Track.inc"  // 
#include "../include/Int/AutoSalon.inc"  // Автосалон
#include "../include/Int/Admin/NewDemorgan.inc"  // Деморган
// Организации
#include "../include/Int/Frac/AO.inc" // Администрация
#include "../include/Int/Frac/PPS.inc" // ППС
#include "../include/Int/Frac/DPS.inc" // ДПС
#include "../include/Int/Frac/FSB.inc" // ФСБ
#include "../include/Int/Frac/KazarmaVH.inc" // ВС
#include "../include/Int/Frac/SMP.inc" // Областная больница
#include "../include/Int/Frac/SMI.inc" // 
// ОПГ 
// Дом
// Гараж
// Бизнес 