
////////////////////////////////////////////////////////////////////////
#define     T_ADMIN        	"`acc_admin`" // - Администраторы
#define     T_BAN		 	"`acc_ban`" // - Таблица бана игроков
#define     T_BAN_IP	 	"`acc_ban_ip`" // - Таблица бана игроков по IP
#define     T_FULL_ADMIN    "`acc_full_admin`" // Администраторы сполным доступом
#define 	T_MEDCARD		"`acc_med_card`" // Таблица с МедКартами игрока
#define 	T_PASPORT     	"`acc_pasport`" // - Таблица паспорта игрока
#define     T_PLAYER        "`acc_player`" // - Таблица с Персонажами
#define     T_QUEST         "`acc_quest`" // - Таблица с квестами
#define     T_ACC_S	        "`acc_server`" // - Таблица c Аккаунтами
#define     T_HISTORY       "`list_history`" // Таблица с наказаниями игрока
#define 	T_ATM			"`server_atm`" // Таблица с банкоматами
#define     T_BANK        	"`server_bank`" // - Таблица банковских счетов
#define     T_BANK_CARDS    "`server_bank_card`" // - Таблица с картами в банке игроков
#define     T_BILBORD   	"`server_bilbord`" // - Таблица с билбордами - рекламными щитами
#define 	T_CARS			"`server_cars`" // Таблица с транспортом игроков
#define 	T_CARS_NUMBER	"`server_cars_number`" //
#define 	T_DEBUG			"`server_debug`" // Таблица с информации о багах
#define 	T_EKONOM   		"`server_ekonomika`" // - Таблица с экономикой сервера
#define 	T_FAMILY		"`server_family`" // Таблица с семьями
#define 	T_FRAC   		"`server_fraction`" // - Таблица с организациями
#define     T_CARFRAC		"`server_fraction_cars`" // - транспорт организации
#define     T_HOUSE         "`server_house`" // Таблица с домами для игрока
#define     T_JOB_SKILL		"`server_job_level`" //
#define 	T_MUSORKI		"`server_musorki`" // Таблица с мусорками
#define     T_PARKING		"`server_parking`" // Подземные парковки
#define     T_PROMO         "`server_promo`" // Таблица с промо-кодами
#define 	T_RADAR			"`server_radar`" // Таблица с радарами
#define     T_SEAT			"`server_seatdowns`" // - 
#define     T_SERVER        "`server_setting`" // - Настройки сервера
#define     T_TAXOPARK      "`server_taxopark`" // - Таблица Таксопарка
#define     T_TAXOPARK_CARS "`server_taxopark_cars`" // - Таблица транспортом Таксопарка
#define 	T_TICKETS		"`server_tickets`" // Таблица с штрафами для игроков
#define     T_TRUDIVAI      "`server_tk`" // - Таблица 
#define     T_VIP			"`server_vip`" // - Таблица
#define     T_TRUCKER   	"`server_trucker`" // - Таблица Транспортной компании
#define		T_PODARKI		"`server_podarki`" // - Таблица с подарками
#define		T_PODAROK		"`acc_podarok`" // - Таблица с 